---

- name: add {{ http_user }} user
  user:
    name: "{{ http_user }}"
    shell: /bin/bash
    comment: "Apache User"
    home: /home/{{ http_user }}
    groups: www-data
    append: 'yes'

- name: Create document directory for {{ http_host }}
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ http_user }}"
    group: www-data
    mode: '0755'

- name: Set up Apache virtualhost for {{ http_host }}
  template:
    src: "config/apache.conf.j2"
    dest: "/etc/apache2/sites-available/{{ http_conf }}"
    owner: root
    mode: '0644'
  notify: Restart Apache

- name: Set up Apache virtualhost for {{ laravel_host }}
  template:
    src: "config/laravel.conf.j2"
    dest: "/etc/apache2/sites-available/{{ laravel_conf }}"
    owner: root
    mode: '0644'
  notify: Restart Apache

- name: Set up Adminer 
  template:
    src: "config/adminer.conf.j2"
    dest: "/etc/apache2/conf-available/adminer.conf"
    owner: root
    mode: '0644'
  notify: Restart Apache

- name: Enable Adminer {{ http_host }}
  command: /usr/sbin/a2enconf adminer.conf
  failed_when: false
  changed_when: false
  notify: Restart Apache

- name: Enable new {{ laravel_host }}
  command: /usr/sbin/a2ensite {{ laravel_conf }}
  failed_when: false
  changed_when: false
  notify: Restart Apache

- name: Disable default Apache site
  command: /usr/sbin/a2dissite 000-default.conf
  failed_when: false
  changed_when: false
  notify: Restart Apache

- name: apache2 listen on port 80
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 80" line="Listen 80" state=present
  notify: Restart Apache

- name: apache2 listen on port 88
  lineinfile: dest=/etc/apache2/ports.conf regexp="^Listen 88" line="Listen 88" state=present
  notify: Restart Apache

- name: Enable new {{ http_host }}
  command: /usr/sbin/a2ensite {{ http_conf }}
  failed_when: false
  changed_when: false
  notify: Restart Apache




# - name: php info page
#   template:
#     src: "config/info.php.j2"
#     dest: "/var/www/{{ http_host }}/info.php"
#     owner: "{{ http_user }}"
#     group: www-data
#     mode: '644'

- name: simple html page
  template:
    src: "config/index.html.j2"
    dest: "/var/www/{{ http_host }}/index.html"
    owner: "{{ http_user }}"
    group: www-data
    mode: '644'

- name: Enable the Apache2 module proxy_fcgi for php to work
  community.general.apache2_module:
    state: present
    name: proxy_fcgi
  become: True

- name: Enable the Apache2 module rewrite 
  community.general.apache2_module:
    state: present
    name: rewrite
  become: True

- name: ensure apache is restarted
  service:
    name: apache2
    state: restarted
  become: True