---
- name: install packages
  apt:
    name:
      - apache2
      - default-mysql-server
      - python3-pymysql
      - ufw
      - python3
      - python3-pymysql
      - vim
      - git
      - tree
      - curl
      - wget
      - adminer
      - w3m
      - php-zip
      - pv
      - gnupg
    state: present
    cache_valid_time: 3600


- name: Add dependencies for PHP versions (Debian).
  apt:
    name:
      - apt-transport-https
      - ca-certificates
    state: present
  become: True

- name: Add Ondrej Sury's apt key (Debian).
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    id: 15058500A0235D97F5D10063B188E2B695BD4743
    state: present
  become: True

- name: Add Ondrej Sury's repo (Debian).
  apt_repository:
    repo: "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
    state: present
  register: php_ondrej_debian_repo
  become: True

- name: Update apt caches after repo is added (Debian).
  apt: update_cache=true
  when:
    - php_ondrej_debian_repo.changed
  become: True

- name: install php 8.0 packages
  apt:
    name:
      - php8.1
      - php-mysql
      - libapache2-mod-php
      - php8.1-mysql
      - php8.1-cli
      - php8.1-common
      - php8.1-snmp
      - php8.1-ldap
      - php8.1-curl
      - php8.1-mbstring
      - php8.1-zip
      - php8.1-tidy
      - php8.1-opcache
      - php8.1-xml
      - php8.1-fpm 
      - php8.1-zip
      - php8.1-curl
      - php8.1-curl
      - libapache2-mod-php8.0
    state: present
    cache_valid_time: 3600
  become: True

- name: Enable the Apache2 module proxy_fcgi for php to work
  community.general.apache2_module:
    state: present
    name: proxy_fcgi
  become: True

- name: ensure apache is restarted
  service:
    name: apache2
    state: restarted
  become: True


- name: Download composer installer
  get_url:
    url: 'https://getcomposer.org/installer'
    dest: '/tmp/composer-installer.php'
    mode: 0755

- name: 'Install composer'
  shell: php composer-installer.php && mv composer.phar {{ composer_install_path }}
  args:
    creates: '{{ composer_install_path }}'
    chdir: /tmp

- name: 'Set composer chmod'
  file:
    path: '{{ composer_install_path }}'
    owner: root
    group: root
    mode: 0755

